project:
  type: website
  output-dir: _html


execute:
  freeze: true

bibliography: bibliography.bib
csl: elsevier-harvard.csl

website:
  favicon: "images/logo.png"
  site-url: "https://rootmemo.github.io"
  search: 
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: "images/logo.png"
    logo-href: /index.qmd
    left:
      - text: "Home"
        file: index.qmd
      - text: "About us"
        file: about.qmd
      - text: "Book"
        file: book.qmd
      - text: "Software"
        file: software.qmd
      - text: "Contact"
        file: contact.qmd
    right:
      - icon: globe
        href: https://rootmemo.github.io
      - icon: github
        href: https://github.com/rootmemo

  sidebar:
    - id: documentation
      title: "Documentation"
      contents:
        - docs/00_tutorial.ipynb
    - id: wiki
      title: "Wiki"
      contents:
        - wiki/index.qmd

  page-footer:
    background: dark
    border: true
    center: "Contact : [**Anil Yildiz**](mailto:yildiz@mbd.rwth-aachen.de) | [**Gerrit J. Meijer**](mailto:gjm36@bath.ac.uk)"
    #right: "[![](/images/logo_mbd.png){width=200px fig-alt=MBD  }](https://www.mbd.rwth-aachen.de)" 

  repo-url: https://www.github.com/rootmemo/rootmemo.github.io
  repo-actions: none
  repo-branch: main
  repo-link-target: "_blank"

format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    css: styles.css
    toc: true
    code-block-bg: true
    code-copy: true

  
